### ISSUE TITLE
How to realize the vertical wind field superposition of RHI scanning

### ISSUE THREAD

**Issue by wanghui0225** [nasa/MultiDop#17]
RHI scan is a distance and height scan in a single direction. How to superimpose vertical wind field? Thank you！

**Comment by tjlang** [comment]
If using RHIs, MultiDop would require as input RHI-based volumes (e.g., contiguous sector of RHI scans) interpolated to Cartesian grids. Note that MultiDop has been made obsolete by PyDDA: https://github.com/openradar/PyDDA. You are encouraged to use that package instead.

**Comment by wanghui0225** [comment]
> If using RHIs, MultiDop would require as input RHI-based volumes (e.g., contiguous sector of RHI scans) interpolated to Cartesian grids. Note that MultiDop has been made obsolete by PyDDA: https://github.com/openradar/PyDDA. You are encouraged to use that package instead.

I will follow your suggestion, thank you very much！
