### ISSUE TITLE
return value type does not match function type - file:coverage.c

### ISSUE THREAD

**Issue by skhobahi** [nasa/MultiDop#8]
**File Name**: _/MultiDop/src/coverage.c_
**Function Name**(Line:224): _static int cvg_idx_s(int, char [MAX_RADARS][PATH_LEN_MAX])_

The above mentioned function is returning an _unsigned int_ variable; however, the type of the function is _integer_. Usually, this can lead to erroneous behavior. I suggest to match the function type and the returned variable _h_.
(Happy to PR if you feel appropriate.)

**Comment by tjlang** [comment]
Yes, please go ahead and do a PR for this. Thanks!

**Comment by tjlang** [comment]
Addressed by https://github.com/nasa/MultiDop/pull/9
